-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgFdZ+cXV2bTiz+NzJwUyFhezvS0smIwqFXPSzF8CugQugCgYIKoZIzj0DAQehRANCAAQa0mzba/RQKFF3UjMUO5cG5/evDKSGp7IHfIkbnMA4PQU60BHWXnxeMDrZfI3nsDZyK4D3vsp1k46DYIJqqX5U
-----END PRIVATE KEY-----